### ISSUE TITLE
MariaDB connection not available in PowerBI

### ISSUE THREAD

**Issue by medvedicatest** [mariadb-corporation/mariadb-powerbi#13]
Please, help me, must be doing something wrong.
Trying to connect PowerBI desktop to mariadb hower this connection type is not contained in the list of available connections even after completion of adapter installation:

https://mariadb.com/resources/blog/getting-started-with-the-mariadb-direct-query-adapter-for-microsoft-power-bi/

any clue how can this be resolved? Has anyone experienced it?

thanks!

**Comment by ilyagithub1** [comment]
Please use the latest version of Microsoft Power BI Desktop.
It includes MariaDB Connector for Power BI.

https://www.microsoft.com/en-us/download/details.aspx?id=58494

Thank you.
