### ISSUE TITLE
Excessively slow data access

### ISSUE THREAD

**Issue by EDgit2022** [mariadb-corporation/mariadb-powerbi#20]
Greetings,

I try to access a MariaDB server from PowerBI and experience some major response times.

In a blank report, connecting to any database takes between 5 and 10 minutes to get the list of tables, followed with a solid hour to fetch the selected table preview.

When I query the server through HeidiSQL I don't notice any performance issues.

The server is running MariaDB 10.1.34, PowerBI is up to date and we installed MariaDB ODBC Driver 64-bit v3.1.15.

Any suggestions to figure out this issue?

Regards,

Eric.

**Comment by EDgit2022** [comment]
I have just stumbled upon an [issue](https://jira.mariadb.org/browse/MDEV-28410) on MariaDB JIRA that completely matches my situation and supect the issuer is using the same ERP we do. Apparently, the MariaDB connector doesn't offer the option "Include relationship columns" which should be disabled when using MyISAM databases.

**Comment by ilyagithub1** [comment]
@EricD-TLZ Thank you for your feedback.

Could you please check if the fix in #19 addresses your issue?

The symptoms you describe here look very similar.
In #19 there is attached a beta version of the fix in the _MariaDB.MEZ_ file and instructions how to use the MEZ file.

The beta version of the Connector has the additional **Auto-detect foreign key dependencies** boolean parameter. Setting it to FALSE should increase performance.

**Comment by EDgit2022** [comment]
@ilyagithub1 Thank you for pointing that out, I tried it and it does indeed solve the issue. I hope the update rolls out soon.
