### ISSUE TITLE
Write Queries Directly

### ISSUE THREAD

**Issue by marcoshw** [mariadb-corporation/mariadb-powerbi#22]
Hello!

Does this connector allows to write raw queries? I can't figure how to do it.

Thanks!

**Comment by arjobsen** [comment]
I have the same request. I wish to run a SQL query which joins tables over multiple databases and tables. Getting the data in import mode would be just fine. I don't want to do the logic in Power Query.

**Comment by ilyagithub1** [comment]
@marcoshw and @arjobsen Thank you for reporting the issue.

_MariaDB data source_ configuration dialog box has been updated to include the **SQL statement** optional parameter.

![Issue-22-Connector-UI-update](https://user-images.githubusercontent.com/42575359/208676491-b93963e4-93fe-4a8e-8a2d-0c1375845c65.png)

**Important!**

- "SQL statement" is support in _Import_ mode only.
- "SQL statement" requires a valid value in the "Database" field.

The updated MariaDB Power BI Connector will be included in an upcoming release of Power BI.

You can start using the new "SQL statement" feature right away by downloading the Beta MEZ file from the attachment here:
[MariaDB-1.0.7-Beta.zip](https://github.com/mariadb-corporation/mariadb-powerbi/files/10268707/MariaDB-1.0.7-Beta.zip)

Please follow the [MEZ file deployment instructions here](https://github.com/mariadb-corporation/mariadb-powerbi/issues/19#issuecomment-1146860048) (look for the phrase "_Put the MEZ file to your"_ there).

**Comment by arjobsen** [comment]
This is great!

I'm currently using `ODBC.Query("database=<database_name>;dsn=<odbc_data_source_name>", "SQL statement")`. It requires setting up an ODBC Data Source in Windows, which in turn requires installing the MySQL driver for Windows. This will elimate those prerequisites.

**Comment by ilyagithub1** [comment]
@arjobsen I'm glad to hear it helps!

And you did it absolutely right. The `ODBC.Query` function is exactly what the updated MariaDB Power BI Connector uses behind the scenes when the `query` parameter is provided.
