### ISSUE TITLE
Unable to find connector in Power BI Desktop

### ISSUE THREAD

**Issue by calechko** [mariadb-corporation/mariadb-powerbi#23]
We are using Power BI Desktop (September 2022). We downloaded the ODBC connector for Windows (both 32 and 64 bit) and no matter how many times we try, including reboots, we are unable to find the MariaDB connector in Power BI Desktop. This is with ODBC Connector 3.1.17. Can you help?

**Comment by ilyagithub1** [comment]
@calechko thank you for your question.

MariaDB Connector should be available in all latest (2022) versions of Power BI Desktop.

Please try the following:

1. In Power BI Desktop toolbar, click the **Get data** button.
2. In the _Get data_ menu, choose the option **More...**. This opens the _Get Data_ dialog.
3. In the _Get Data_ dialog, type "maria" into the search field. This should find and display the MariaDB connector in the short list.

See the screenshots below.
The screenshots have been taken in the latest Power BI Desktop version: 2.110.805.0 64-bit (October 2022).

![Issue-23-screenshot-1](https://user-images.githubusercontent.com/42575359/196999325-3bec175a-5aa0-44b8-823d-95f926213b4a.png)
![Issue-23-screenshot-2](https://user-images.githubusercontent.com/42575359/196999330-7a4cc29b-ed05-459d-b8ec-f4f7d2f95341.png)


If this does not help, please describe your actions in greater detail step by step and supply screenshots.

Thank you for using MariaDB Connector for Power BI.
