### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by alicelee999** [mariadb-corporation/mariadb-powerbi#24]
I have problem to connect to MariaDB from Power BI using ODBC connector

![PowerBI-MariaDB-connector-issue](https://user-images.githubusercontent.com/12386254/200726673-25186511-1468-4c29-a5f4-e630384d1243.PNG)

Not sure why?

Thanks.

**Comment by ilyagithub1** [comment]
@alicelee999 It seems that MariaDB ODBC Driver is not installed on your system. This driver is a prerquisite for MariaDB Power BI Connector.

Please download and install the driver. Then try again.

MariaDB ODBC Driver download page:
https://mariadb.com/kb/en/mariadb-connector-odbc/

Thank you.
