### ISSUE TITLE
Query contains unsupported function

### ISSUE THREAD

**Issue by MateusFiel** [mariadb-corporation/mariadb-powerbi#25]
Today (07-dec-2022) I can no longer update the dataset automatically. The message appears stating that the data source does not support the update.

**Comment by ilyagithub1** [comment]
@MateusFiel There is insufficient information in your request to process it.

Please describe your problem in detail:

- What are the Steps to Reproduce?
- What is the actual outcome (or result)?
- What was your expected outcome (or result)?

Please supplement your description with Power BI trace logs.

You may consult this article that explains **How to find error details in Power BI Desktop with Diagnostic Tracing**:
https://github.com/mariadb-corporation/mariadb-powerbi/wiki/How-to-find-error-details-in-Power-BI-Desktop-with-Diagnostic-Tracing
