### ISSUE TITLE
Invalid Connection Credentials

### ISSUE THREAD

**Issue by sarabjeetsinghlenskart** [mariadb-corporation/mariadb-powerbi#26]
We are currently using MariaDB driver 3.01.15.00 in our systems and while refreshing our PowerBI reports, we sometimes get invalid connection credentials error in PowerBI. On reaching to the Microsoft support team, they suggested to check with the MariaDB support team for the latest driver.

Could you please help in this matter ?

**Comment by ilyagithub1** [comment]
@sarabjeetsinghlenskart Thank you for your question. You are in the right place.

Could you please upgrade your MariaDB ODBC Driver to the latest version 3.1.17?

Here is the link to the driver download page:
https://mariadb.com/kb/en/mariadb-connector-odbc/

If the issue persists with the latest driver version then feel free to reopen this issue.

When reopening, please attach Power BI trace logs.

Here is a link to the article that explains how to collect Power BI trace logs:
[How to find error details in Power BI Desktop with Diagnostic Tracing](https://github.com/mariadb-corporation/mariadb-powerbi/wiki/How-to-find-error-details-in-Power-BI-Desktop-with-Diagnostic-Tracing)
