### ISSUE TITLE
Problem uploading Power BI Report to Power BI Service Portal

### ISSUE THREAD

**Issue by sbronchu** [mariadb-corporation/mariadb-powerbi#28]
I'm working with Power BI desktop and MariaDB without problems, but when I upload the report to the service portal I can't configure any gateway.

Please, How I can connect my report in the portal with de source of data?

Thank you on advance.

**Comment by ilyagithub1** [comment]
@sbronchu Based on your description where you mention a gateway, you are trying to use an on-premise MariaDB database in Power BI Online.

Power BI Gateway is a piece of software that needs to be installed and configured separately. Gateway is a feature of Power BI and it fully supports MariaDB Power BI Connector.

Please follow the general instructions in the Microsoft article ["What is an on-premises data gateway?", section "Use a gateway"](https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-onprem#use-a-gateway).

For more advanced Power BI Gateway use cases, please consult the article ["Guidance for deploying a data gateway for the Power BI service"](https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-deployment-guidance).

Thank you for using MariaDB Power BI Connector.
