### ISSUE TITLE
Syntax error with if statement

### ISSUE THREAD

**Issue by Akos90** [mariadb-corporation/mariadb-powerbi#3]
When using "contains" in the "add conditional column" dialog, the query runs on syntax error:
![image](https://user-images.githubusercontent.com/8739106/103774858-86306100-502d-11eb-8a13-03a63460d74c.png)

corresponding M code:
![image](https://user-images.githubusercontent.com/8739106/103775050-cdb6ed00-502d-11eb-974c-8957f9464696.png)

Datasource is in import mode!

**Comment by ilyagithub1** [comment]
@Akos90 Could you please provide more details about the query?

More information is required to reproduce this issue, for example:

- A zip with Power BI Desktop traces. See [How to generate Power BI Desktop traces?](https://support.biconnector.com/support/solutions/articles/8000082215-how-to-generate-power-bi-desktop-traces-) for instructions. Remember to click **Clear Traces folder** before tracing is enabled. This will minimize the size of the logs.
- The complete M query.

### Preliminary analysis

There's no error in your M line of code or the SQL quoted in the driver's error message. Both code snippets are correct.

The SQL syntax issue might originate from the rest of the query that surrounds the quoted snippet.

Possible causes for the SQL syntax issue:

- A line break or a special symbol.
- A collation issue.

With more details available about the original query yielding the error a more definitive response could be provided.
