### ISSUE TITLE
Cannot download connector from linked page

### ISSUE THREAD

**Issue by tasso85** [mariadb-corporation/mariadb-powerbi#32]
The link in the homepage to download the connector (https://mariadb.com/downloads/#connectors-connectors_dataanalysis) does not seem to work, it brings you to the page to download the various connectors but there is no option for "data analysis" nor "power bi" or similar.

How can one download the connector, given that it seems to be not available with "plain" PowerBI Desktop?

**Comment by toddstoffel** [comment]
The connector has been certified by Microsoft and is now embedded in Power BI directly.

**Comment by tasso85** [comment]
Ah, I see... Sadly, from what I can see, the certified connector still does not support the option to perform a custom query, is that right? Will that ever be supported?

As of now we are using version 1.0.7-beta, which provides that feature; however, I do not really feel confident using an unmaintained beta version.
