### ISSUE TITLE
Help with MariaDB Direct Query Adapter for Microsoft Power BI

### ISSUE THREAD

**Issue by Scotto13** [mariadb-corporation/mariadb-powerbi#6]
I have tried the MariaDB connector on my pc and it works great.  
Can I please get directions on how to install the adapter on my OnPremise Gateway in order to build reports on my PowerBI desktop and publish them to the gateway?  

I installed the connection to my MySQL db on the Gateway but I don't know how to build reports (on PBI desktop) using that connection.  Any help is greatly appreciated.  

Thank you,
Scott Williams

**Comment by ilyagithub1** [comment]
Hello Scott,

Thanks for posting a good question.

Steps to install and use MariaDB Power BI Connector with Power BI On-premises Data Gateway:

1. (_Optional_ - skip if the ODBC driver is already installed) [Download](https://mariadb.com/kb/en/mariadb-connector-odbc/) and install MariaDB ODBC Driver v3.1.7 or later.
2. [Download](https://mariadb.com/downloads/#connectors-connectors_dataanalysis) MariaDB Power BI Connector from mariadb.com
3. Unpack the downloaded MariaDB Power BI Connector package.
4. Copy the MEZ file to the Gateway's **Custom data connectors** directory on the target computer.
   1. To find the destination directory path, open _One-premises data gateway_ configuration application, tab **Connectors** (see the screenshot).
   ![Custom data connectors](https://user-images.githubusercontent.com/42575359/106315031-4e56bb00-6273-11eb-8a91-c6b09d29b73e.png)
   2. In Standard Mode the path should look like this - copy the MEZ file here:
   ```
   C:\Users\PBIEgwService\Documents\Power BI Desktop\Custom Connectors
   ```
   3. After the file is copied to the location above the **Custom data connectors** screen should update shortly (in a few seconds usually).
![MariaDBCustomConnectorInstalled](https://user-images.githubusercontent.com/42575359/106315994-bb1e8500-6274-11eb-8703-fb20557e5c25.png)
5. Set up a MariaDB data source in Power BI Online:
   1. In a browser navigate to Power BI Online [app.powerbi.com](https://app.powerbi.com/)
   2. In Power BI Online in the upper right corner click **Settings** > **Manage gateways** This should open the GATEWAY CLUSTERS page.
   3. Make sure you see your gateway in the list. If you don't you need to [troubleshoot the gateway](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-onprem-tshoot).
![Gateways](https://user-images.githubusercontent.com/42575359/106317553-2406fc80-6277-11eb-8985-795506d7b3d6.png)
   4. Click **ADD DATA SOURCE**.
   5. In the **Data Source Type** drop-down list select _MariaDB data source_.
![AddDataSource](https://user-images.githubusercontent.com/42575359/106317890-a099db00-6277-11eb-86a2-b866e5091cad.png)
   6. In the **MariaDB data source** field provide a value that matches exactly to the data source value as visible in the _Data source settings_ dialog in Power BI Desktop.
      1. Note that the data source value may optionally contain the server port and/or database name, e.g. `myserver:3306` or `myserver;flights` or `myserver:3306;flights`.
      2. Double-check that the _MariaDB data source_ values match in Power BI Desktop and Power BI Online.
![MariaDBdatasource](https://user-images.githubusercontent.com/42575359/106318733-033fa680-6279-11eb-9ccd-fbedf0841208.png)

   7. Provide values for _Username_, _Password_ and other settings, like _Encrryption_, as necessary and click **Add**. This will create and test your MariaDB data source in Power BI Online.
![ConnectionSuccessful](https://user-images.githubusercontent.com/42575359/106319793-aa710d80-627a-11eb-8f3d-5e2b6d16c476.png)
6. In Power BI Desktop click **Publish** to publish your report with the MariaDB data source to Power BI Online.
7. Test the report Power BI Online [app.powerbi.com](https://app.powerbi.com/). It should successfully fetch the data from your MariaDB on-premise database via the Gateway using the MariaDB Power BI Connector.
