### ISSUE TITLE
MariaDB connection doesn't allow for full Port Name

### ISSUE THREAD

**Issue by Scotto13** [mariadb-corporation/mariadb-powerbi#8]
I am connected to the MySQL db via Oracle SQL Developer.  The connection uses Port: **3306/?serverTimezone=PST#/billmax**
In the Maria Connection settings, I only am able to put in 3306.  
I think this is causing a connection issue when I publish the report to the PowerBI gateway.  

Also, the MariaDB getting started page says: 
You are now connected to your remote MariaDB database and can choose your data source and run queries and create visuals with Microsoft Power BI.
When I add a table using the data source, it seems that the report becomes InMemory instead of Direct Query.  Can you please direct me to how I add a query on my db in PBI?  

All help is much appreciated!
This tool will really help my company so I'm hopeful on getting it to work.  
Scott Williams

**Comment by ilyagithub1** [comment]
@Scotto13 thank you for using MariaDB Power BI Connector.
Here are answers to your questions.

### Connections Strings

Few things here:

- MariaDB Power BI Connector does not support custom parameters.
- When you connect via Oracle SQL Developer you are using JDBC Driver [MariaDB Connector/J](https://mariadb.com/kb/en/about-mariadb-connector-j/) which supports `serverTimezone` and other [URL parameters](https://mariadb.com/kb/en/about-mariadb-connector-j/#optional-url-parameters).
- MariaDB Power BI Connector uses MariaDB ODBC Driver which is explained in the [Getting Started with MariaDB Direct Query Adapter](https://mariadb.com/resources/blog/getting-started-with-the-mariadb-direct-query-adapter-for-microsoft-power-bi/) page that you refer to. That is a different database driver. The article explains how to configure **port** and **database name**.

### InMemory vs. Direct Query

When you configure the connection to use the **DirectQuery** mode in the _MariaDB data source_ dialog in Power BI Desktop (see the screenshot) the connection shall stay in this mode until it is manually changed.

![MariaDB-data-source-dialog](https://user-images.githubusercontent.com/42575359/107245430-d1c49900-6a37-11eb-9864-b26be5822d3e.png)

To change the mode from **DirectQuery** to **Import** (a.k.a. **InMemory**), in Power BI Desktop click on the label in the bottom right corner. It will display a warning and import all the data.

![PowerBI-Desktop-Storage-Mode-indicator](https://user-images.githubusercontent.com/42575359/107245935-6202de00-6a38-11eb-8fbf-0f9b5df8f429.png)

If you see the "DirectQuery" label in the status bar (bottom right) it means the data model is in **DirectQuery** mode and it will be published and work in DirectQuery mode at all times.

### Can you please direct me to how I add a query on my db in PBI?

In Power BI Desktop a query is created or edited using the **Power Query Editor** that can be launched by clicking the **Transform Data** button in the Ribbon.

![PowerBI-Desktop-Transform-Data-button](https://user-images.githubusercontent.com/42575359/107247188-b0fd4300-6a39-11eb-8829-ec7d0d11c7d6.png)

Power Query Editor window screenshot:
![Power-Query-Editor](https://user-images.githubusercontent.com/42575359/107247608-1e10d880-6a3a-11eb-9a4a-9180eef252dc.png)

More information about Power Query Editor:
[Quickstart: Using Power Query in Power BI Desktop](https://docs.microsoft.com/en-us/power-query/power-query-quickstart-using-power-bi)
